// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/:locale?": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/blogs/:blogHandle/:articleHandle": {
    params: {
      "locale"?: string;
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/:locale?/sitemap/:type/:page.xml": {
    params: {
      "locale"?: string;
      "type": string;
      "page": string;
    };
  };
  "/:locale?/blogs/:blogHandle": {
    params: {
      "locale"?: string;
      "blogHandle": string;
    };
  };
  "/:locale?/collections/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/account/authorize": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/collections": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/policies/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/products/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/account/logout": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/collections/all": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/policies": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/login": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/discount/:code": {
    params: {
      "locale"?: string;
      "code": string;
    };
  };
  "/:locale?/pages/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/sitemap.xml": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/blogs": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/orders": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/orders/:id": {
    params: {
      "locale"?: string;
      "id": string;
    };
  };
  "/:locale?/account/addresses": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/profile": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/*": {
    params: {
      "locale"?: string;
      "*": string;
    };
  };
  "/:locale?/search": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/cart": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/cart/:lines": {
    params: {
      "locale"?: string;
      "lines": string;
    };
  };
  "/:locale?/*": {
    params: {
      "locale"?: string;
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/robots.txt" | "/:locale?" | "/:locale?/blogs/:blogHandle/:articleHandle" | "/:locale?/sitemap/:type/:page.xml" | "/:locale?/blogs/:blogHandle" | "/:locale?/collections/:handle" | "/:locale?/account/authorize" | "/:locale?/collections" | "/:locale?/policies/:handle" | "/:locale?/products/:handle" | "/:locale?/account/logout" | "/:locale?/collections/all" | "/:locale?/policies" | "/:locale?/account/login" | "/:locale?/discount/:code" | "/:locale?/pages/:handle" | "/:locale?/sitemap.xml" | "/:locale?/blogs" | "/:locale?/account" | "/:locale?/account/orders" | "/:locale?/account/orders/:id" | "/:locale?/account/addresses" | "/:locale?/account/profile" | "/:locale?/account/*" | "/:locale?/search" | "/:locale?/cart" | "/:locale?/cart/:lines" | "/:locale?/*";
  };
  "routes/[robots.txt].jsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/($locale).jsx": {
    id: "routes/($locale)";
    page: "/:locale?" | "/:locale?/blogs/:blogHandle/:articleHandle" | "/:locale?/sitemap/:type/:page.xml" | "/:locale?/blogs/:blogHandle" | "/:locale?/collections/:handle" | "/:locale?/account/authorize" | "/:locale?/collections" | "/:locale?/policies/:handle" | "/:locale?/products/:handle" | "/:locale?/account/logout" | "/:locale?/collections/all" | "/:locale?/policies" | "/:locale?/account/login" | "/:locale?/discount/:code" | "/:locale?/pages/:handle" | "/:locale?/sitemap.xml" | "/:locale?/blogs" | "/:locale?/account" | "/:locale?/account/orders" | "/:locale?/account/orders/:id" | "/:locale?/account/addresses" | "/:locale?/account/profile" | "/:locale?/account/*" | "/:locale?/search" | "/:locale?/cart" | "/:locale?/cart/:lines" | "/:locale?/*";
  };
  "routes/($locale).blogs.$blogHandle.$articleHandle.jsx": {
    id: "routes/($locale).blogs.$blogHandle.$articleHandle";
    page: "/:locale?/blogs/:blogHandle/:articleHandle";
  };
  "routes/($locale).sitemap.$type.$page[.xml].jsx": {
    id: "routes/($locale).sitemap.$type.$page[.xml]";
    page: "/:locale?/sitemap/:type/:page.xml";
  };
  "routes/($locale).blogs.$blogHandle._index.jsx": {
    id: "routes/($locale).blogs.$blogHandle._index";
    page: "/:locale?/blogs/:blogHandle";
  };
  "routes/($locale).collections.$handle.jsx": {
    id: "routes/($locale).collections.$handle";
    page: "/:locale?/collections/:handle";
  };
  "routes/($locale).account_.authorize.jsx": {
    id: "routes/($locale).account_.authorize";
    page: "/:locale?/account/authorize";
  };
  "routes/($locale).collections._index.jsx": {
    id: "routes/($locale).collections._index";
    page: "/:locale?/collections";
  };
  "routes/($locale).policies.$handle.jsx": {
    id: "routes/($locale).policies.$handle";
    page: "/:locale?/policies/:handle";
  };
  "routes/($locale).products.$handle.jsx": {
    id: "routes/($locale).products.$handle";
    page: "/:locale?/products/:handle";
  };
  "routes/($locale).account_.logout.jsx": {
    id: "routes/($locale).account_.logout";
    page: "/:locale?/account/logout";
  };
  "routes/($locale).collections.all.jsx": {
    id: "routes/($locale).collections.all";
    page: "/:locale?/collections/all";
  };
  "routes/($locale).policies._index.jsx": {
    id: "routes/($locale).policies._index";
    page: "/:locale?/policies";
  };
  "routes/($locale).account_.login.jsx": {
    id: "routes/($locale).account_.login";
    page: "/:locale?/account/login";
  };
  "routes/($locale).discount.$code.jsx": {
    id: "routes/($locale).discount.$code";
    page: "/:locale?/discount/:code";
  };
  "routes/($locale).pages.$handle.jsx": {
    id: "routes/($locale).pages.$handle";
    page: "/:locale?/pages/:handle";
  };
  "routes/($locale).[sitemap.xml].jsx": {
    id: "routes/($locale).[sitemap.xml]";
    page: "/:locale?/sitemap.xml";
  };
  "routes/($locale).blogs._index.jsx": {
    id: "routes/($locale).blogs._index";
    page: "/:locale?/blogs";
  };
  "routes/($locale).account.jsx": {
    id: "routes/($locale).account";
    page: "/:locale?/account" | "/:locale?/account/orders" | "/:locale?/account/orders/:id" | "/:locale?/account/addresses" | "/:locale?/account/profile" | "/:locale?/account/*";
  };
  "routes/($locale).account.orders._index.jsx": {
    id: "routes/($locale).account.orders._index";
    page: "/:locale?/account/orders";
  };
  "routes/($locale).account.orders.$id.jsx": {
    id: "routes/($locale).account.orders.$id";
    page: "/:locale?/account/orders/:id";
  };
  "routes/($locale).account.addresses.jsx": {
    id: "routes/($locale).account.addresses";
    page: "/:locale?/account/addresses";
  };
  "routes/($locale).account.profile.jsx": {
    id: "routes/($locale).account.profile";
    page: "/:locale?/account/profile";
  };
  "routes/($locale).account._index.jsx": {
    id: "routes/($locale).account._index";
    page: "/:locale?/account";
  };
  "routes/($locale).account.$.jsx": {
    id: "routes/($locale).account.$";
    page: "/:locale?/account/*";
  };
  "routes/($locale).search.jsx": {
    id: "routes/($locale).search";
    page: "/:locale?/search";
  };
  "routes/($locale)._index.jsx": {
    id: "routes/($locale)._index";
    page: "/:locale?";
  };
  "routes/($locale).cart.jsx": {
    id: "routes/($locale).cart";
    page: "/:locale?/cart" | "/:locale?/cart/:lines";
  };
  "routes/($locale).cart.$lines.jsx": {
    id: "routes/($locale).cart.$lines";
    page: "/:locale?/cart/:lines";
  };
  "routes/($locale).$.jsx": {
    id: "routes/($locale).$";
    page: "/:locale?/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].jsx");
  "routes/($locale)": typeof import("./app/routes/($locale).jsx");
  "routes/($locale).blogs.$blogHandle.$articleHandle": typeof import("./app/routes/($locale).blogs.$blogHandle.$articleHandle.jsx");
  "routes/($locale).sitemap.$type.$page[.xml]": typeof import("./app/routes/($locale).sitemap.$type.$page[.xml].jsx");
  "routes/($locale).blogs.$blogHandle._index": typeof import("./app/routes/($locale).blogs.$blogHandle._index.jsx");
  "routes/($locale).collections.$handle": typeof import("./app/routes/($locale).collections.$handle.jsx");
  "routes/($locale).account_.authorize": typeof import("./app/routes/($locale).account_.authorize.jsx");
  "routes/($locale).collections._index": typeof import("./app/routes/($locale).collections._index.jsx");
  "routes/($locale).policies.$handle": typeof import("./app/routes/($locale).policies.$handle.jsx");
  "routes/($locale).products.$handle": typeof import("./app/routes/($locale).products.$handle.jsx");
  "routes/($locale).account_.logout": typeof import("./app/routes/($locale).account_.logout.jsx");
  "routes/($locale).collections.all": typeof import("./app/routes/($locale).collections.all.jsx");
  "routes/($locale).policies._index": typeof import("./app/routes/($locale).policies._index.jsx");
  "routes/($locale).account_.login": typeof import("./app/routes/($locale).account_.login.jsx");
  "routes/($locale).discount.$code": typeof import("./app/routes/($locale).discount.$code.jsx");
  "routes/($locale).pages.$handle": typeof import("./app/routes/($locale).pages.$handle.jsx");
  "routes/($locale).[sitemap.xml]": typeof import("./app/routes/($locale).[sitemap.xml].jsx");
  "routes/($locale).blogs._index": typeof import("./app/routes/($locale).blogs._index.jsx");
  "routes/($locale).account": typeof import("./app/routes/($locale).account.jsx");
  "routes/($locale).account.orders._index": typeof import("./app/routes/($locale).account.orders._index.jsx");
  "routes/($locale).account.orders.$id": typeof import("./app/routes/($locale).account.orders.$id.jsx");
  "routes/($locale).account.addresses": typeof import("./app/routes/($locale).account.addresses.jsx");
  "routes/($locale).account.profile": typeof import("./app/routes/($locale).account.profile.jsx");
  "routes/($locale).account._index": typeof import("./app/routes/($locale).account._index.jsx");
  "routes/($locale).account.$": typeof import("./app/routes/($locale).account.$.jsx");
  "routes/($locale).search": typeof import("./app/routes/($locale).search.jsx");
  "routes/($locale)._index": typeof import("./app/routes/($locale)._index.jsx");
  "routes/($locale).cart": typeof import("./app/routes/($locale).cart.jsx");
  "routes/($locale).cart.$lines": typeof import("./app/routes/($locale).cart.$lines.jsx");
  "routes/($locale).$": typeof import("./app/routes/($locale).$.jsx");
};